# User

my_username: dustin
my_home: /home/dustin

# Software

my_github_username: bashfulrobot
xmind_version: 10.1.2-202004142327

# Fonts

font_awesome_version: 5.13.0

# System
my_timezone: America/Vancouver
laptop_hostname: xps
