### Increase fs.inotify.max_user_watches = 524288
# Needed so that vscode can monitor larger workspaces
# If ram is a contraint - may want to lower
- name: Modify fs.inotify.max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present