- name: Placing insync autostart
  copy:
    src: files/cfg/home/.config/autostart/insync.desktop
    dest: "/home/{{ my_username }}/.config/autostart/insync.desktop"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644

- name: Placing seafile autostart
  copy:
    src: files/cfg/home/.config/autostart/seaf-cli.desktop
    dest: "/home/{{ my_username }}/.config/autostart/seaf-cli.desktop"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644

- name: Placing auto-cpufreq autostart on Laptop
  copy:
    src: files/cfg/home/.config/autostart/auto-cpufreq.desktop
    dest: "/home/{{ my_username }}/.config/autostart/auto-cpufreq.desktop"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644
  when:
  # Each line is treated as "AND"
    - ansible_distribution == "Ubuntu"
    # Variables use no {{}} or quotes in conditionals
    - ansible_hostname == laptop_hostname

- name: Placing xbanish autostart
  copy:
    src: files/cfg/home/.config/autostart/xbanish.desktop
    dest: "/home/{{ my_username }}/.config/autostart/xbanish.desktop"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode: 0644