- name: Add Docker's public PGP key to the APT keyring
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/ubuntu/gpg"

# Hard code release so that it will work on 20.04
# When Docker supports officially - need to change
- name: Configure Docker's upstream APT STABLE Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable"
    update_cache: true

- name: Remove Old Docker APT Packages (Ubuntu/Debian)
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install Docker CE
  apt:
    name: "{{ dockerpackages }}"
    state: "present"
  vars:
    dockerpackages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
