- name: Add Pop Theme PPA
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - ppa:bashfulrobot/pop-theme

- name: Install POP theme Packages
  apt:
    name: "{{ poppackages }}"
  vars:
    poppackages:
      - pop-gtk-theme
      - pop-icon-theme
      - pop-fonts

- name: Set Window Tile Font
  become: true
  become_user: "{{ my_username }}"
  dconf:
      key: "/org/gnome/desktop/wm/preferences/titlebar-font"
      value: "'Fira Sans Semi-Bold 10'"
      state: present

- name: Set Documents Font
  become: true
  become_user: "{{ my_username }}"
  dconf:
      key: "/org/gnome/desktop/interface/document-font-name"
      value: "'Roboto Slab 11'"
      state: present

- name: Set Interface Font
  become: true
  become_user: "{{ my_username }}"
  dconf:
      key: "/org/gnome/desktop/interface/font-name"
      value: "'Fira Sans Semi-Light 10'"
      state: present

- name: Set Monospace Font
  become: true
  become_user: "{{ my_username }}"
  dconf:
      key: "/org/gnome/desktop/interface/monospace-font-name"
      value: "'Fira Mono 11'"
      state: present